version: '3'
services:
  webhook-relay:
    container_name: webhookrelay
    image: webhookrelay/webhookrelayd-arm:latest
    network_mode: host
    restart: always
    env_file:
      - .env
  hdmi-service:
    build: .
    ports:
        - "5000:5000"
    env_file:
      - .env
    restart: always
    volumes: 
      - .:/usr/src/app
    devices:
      - "/dev/vchiq:/dev/vchiq"
